config/routes.rb
Rails.application.routes.draw do
  resources :ips
  resources :ads
	resources :users
	resources :tags
	resources :products
	resources :bank_infos
	resources :invoices
	resources :feedbacks
	resources :payment_cards
	resources :suggestion_tables
	
	root 'static_pages#home'
	
    get 'signup'  => 'users#new'	
    get 'details' => 'users#edit_personal_details'
    get 'preferences' => 'users#edit_preferences'
    get 'verify_email' => 'users#verify_email'
    get 'terms_and_conditions' => 'static_pages#terms_and_conditions'
    get 'help' => 'static_pages#help'
    get 'api' => 'static_pages#api'
    get 'verification_success' => 'static_pages#verification_success'
    get 'resend_verification_email' => 'users#resend_verification_email'
    get 'login' => 'sessions#new'
    post   'login'   => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'
	
	get 'inc_font' => 'users#inc_font'
	get 'dec_font' => 'users#dec_font'
	
	get 'list_tags' => 'tags#list_tags'
	get 'block_tags' => 'tags#block_tags'
	get 'block' => 'tags#block_tags_action'
    
    get 'upload' => 'ads#new'
    get 'block_ad_in_product' => 'ads#single_ad_block'
    delete 'delete_ad' => 'ads#destroy'
    get 'search' => 'ads#search'
    get 'edit' => 'ads#edit'
    
    get 'add_product' => 'products#new'
    get 'products' => 'products#index'
    get 'delete_products' => 'products#destroy'
    
    get 'add_bank_details' => 'bank_infos#new'
    get 'withdraw_revenue' => 'users#withdraw_revenue'
    post 'withdraw' => 'invoices#withdraw_revenue'
    
    get 'single_ad' => 'ads#get_ad'
    get 'random_ad' => 'ads#get_random_ad'
    get 'random_ad_tags' => 'ads#get_random_ad_by_tags'
    get 'suggested_ad' => 'ads#suggested_ad'
    get 'click_ad' => 'ads#click_ad'
    
    get 'leave_feedback' => 'feedbacks#new'
    
    get 'successful_withdrawal' => 'invoices#successful_withdrawal'
    get 'generate_invoice_pdf' => 'invoices#generate_invoice_pdf'
    
    get 'top_up' => 'users#top_up'
    post 'top_up_action' => 'users#top_up_action'
    
    get 'add_payment_card' => 'payment_cards#new'
    
    get 'pay_bills' => 'users#pay_bills'
    get 'bill_pay_invoice' => 'users#bill_pay_invoice'
    get 'generate_bill_pay_invoice_pdf' => 'users#generate_bill_pay_invoice_pdf'
    post 'pay_bills_action' => 'users#pay_bills_action'
    
    get 'performance_analysis' => 'users#performance_analysis'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
	if current_user != nil
		if current_user.banned == false
			if cookies[:first_session_visit] == nil
				cookies[:first_session_visit] = { value: false, expires: 2.hours.from_now }
				flash[:success] = "Welcome Back!"
				redirect_to current_user
			else
				redirect_to current_user
			end
		else
		end
	end
  end

  def uploaded
  end
  
  def verification_success
  end
  
  def terms_and_conditions
  end
  
  def api
  end

end

app/views/static_pages/api.html.erb
<% provide(:title, 'API') %>
<h1>API</h1>
<p>
Please do not forget to create a free account and register your software product. Otherwise, you will not able to embed the API in your project.
</p>
Downloads:
<ul class="api-download-list">
<li><%= link_to "JAVA API", '/data/JAVA_API.zip' %></li>
<li><%= link_to "PHP API", '/data/PHP_API.zip' %></li>
</ul>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	<b>Table of Contents</b>
	<ul class="toc">
	<li><a href="#registration">Registration</a></li>
	<li><a href="#upload">Ad Upload</a></li>
	<li><a href="#product">Product Creation</a></li>
	<li><a href="#product_block_tag">Blocking Tags In Products</a></li>
	<li><a href="#product_block_ad">Blocking Ads In Products</a></li>
	<li><a href="#bills">Paying Bills</a></li>
	<li><a href="#top_up">Topping Up Account Balance</a></li>
	<li><a href="#revenue">Revenue Withdrawal</a></li>
	<li><a href="#api">Embedding Service In Software Product</a></li>
	<li><a href="#costs">Ads Serving Costs For Publishers</a></li>
	<li><a href="#ad_rev">Software Developer Revenue</a></li>
	<li><a href="#ad_block">AdBlock</a></li>
	</ul>
	<br/>
	<b id="registration">Registration</b>
	<br/>
	In order to create a free user account, please click the <b>Sign Up!</b> button located at the home page and you will be redirected to the registration page. 
	Alternatively, click the <b>Log in</b> link located in the navigation bar at the top of the screen. You will be redirected to the log in page. Here, click 
	the <b>Sign up now!</b> link located just below the <b>Log in</b> button. Shortly, you will be redirected to the registration page.
	<br/>
	The registration form will require you to provide the following information:
	<ul>
	<li>Login - a username you will use to log into the service.</li>
	<li>Full name</li>
	<li>Company name</li>
	<li>User type - if you wish to advertise a product or a service, please select the <b>Ad Publisher</b> option.
	Otherwise, if you are a software developer and wish to incorporate the <b>AdPush</b> service into your product, please select the
	<b>Software Developer</b> option.</li>
	<li>Gender</li>
	<li>Date of birth - you must be at least 13 years old in order to use the service.</li>
	<li>Country</li>
	<li>Region</li>
	<li>City</li>
	<li>Zip Code</li>
	<li>Address</li>
	<li>Email</li>
	<li>Password</li> 
	</ul>
	After the registration is complete, the account verification email will be dispatched to the provided email address. You can always request the redispatchment of the email.
	You can also change the account's email address if you experience any issues with verifying the current email address.<br/>
	After you verify your account, you will be able to use the service.
	<br/><br/>

	<b id="upload">Ad Upload</b>
	<br/>
	In order to upload an ad, please access your ad publisher account. At the control panel (the very first page that appears after the authorisation),
	click the <b>Upload New Ad</b> button. 
	<br/>
	The ad upload form will require you to provide the following information:
	<ul>
	<li>Text - the description of the ad, or a slogan.</li>
	<li>Link</li>
	<li>Tags</li>
	<li>Targeted countries - the ad will not be served in the territories excluded from the list.</li>
	<li>Minimum age - the ad will not be served to the users younger than the specified minimum age.</li>
	<li>Maximum age - the ad will not be served to the users older than the specified maximum age.</li>
	</ul>
	Optionally, you can also upload a static image in <b>PNG</b> format or an animation in <b>GIF</b> format.
	<br/>
	After the new ad is uploaded, you will be redirected to the ad's page, where its details are listed.
	<br/><br/>

	<b id="product">Product Creation</b>
	<br/>
	In order to add new software product, please access your software developer account. At the control panel, click the 
	<b>Add New Software Product</b> button. After the redirect, type in your software product's title and click the 
	<b>Add Product</b> button. You will then be redirected to the page listing all software products added by the current user and notified of
	the new product's creation with the <b>New Software Product Added</b> message.
	<br/><br/>

	<b id="product_block_tag">Blocking Tags In Products</b>
	<br/>
	In order to restrict serving of the ads described with the specific tags to a product, please access your software developer account. At the control panel,
	click the <b>List Software Products</b> button. You will be redirected to the page listing all software products added by the current user.
	Select the products in which the restriction is to be carried out and click the <b>Block Tags In Selected Products</b> button. You will be redirected
	to the block selection page. Under the relevant product heading, please select the tags to be blocked. When you are done, click the
	<b>Block Selected Tags</b> button. You will be notified that the tags were blocked with the <b>Block Settings Updated</b> message.
	<br/><br/>

	<b id="product_block_ad">Blocking Tags In Ads</b>
	<br/>
	In order to restrict serving of a specific ad to a product, please access your software developer account. At the control panel, issue an ads search request via
	a search box. Among the search results, find the required ad and click the block ad icon (<%=image_tag('block.png', width: 16, height: 16, style: 'margin-bottom: 7px;')%>).
	A pop-up listing the products added by the current user will appear. Select the products in which the restriction is to be carried out and click the <b>Block Ad In Selected Products</b> button.
	You will be notified that the ad was blocked with the <b>Ad {ID} Block Parameters Modified</b> message.
	<br/><br/>

	<b id="bills">Paying Bills</b>
	<br/>
	If the ad publisher's bills for the previous months have not been paid, the <b>Bills For Previous Months Unpaid - Published Ads Won't Be Served</b> message will appear at the control panel.
	In order to pay the bills, click the <b>Pay Bills</b> button. You will be redirected to the bills pay page. Here, select the bill to be paid and the payment card to use (if none is associated with your account,
	you will be prompted to add one), enter the CVV/CVC, and click the <b>Pay The Bill</b> button. If the transaction is successful, you will be redirected to the bill payment notification page
	where you can download the invoice.

	<br/><br/>

	<b id="top_up">Topping Up Account Balance</b>
	<br/>
	As an ad publisher, you might want to use the opportunity to prepay your ads by topping up the account balance and receive a discount.
	In order to top up the account balance, access the control panel and click the <b>Top Up</b> button. You will be redirected to the top up page. Here, type in the top up amount and select the payment card to use (if none is associated with your account,
	you will be prompted to add one), then enter the CVV/CVC and click the <b>Top Up</b> button. If the transaction is successful, you will be redirected back to the control panel and notified so with the <b>Successful Top Up!</b> message.
	<br/><br/>

	<b id="revenue">Revenue Withdrawal</b>
	<br/>
	In order to withdraw the generated revenue, please access your software developer account. At the control panel, click the <b>Withdraw Revenue</b> button.
	You will be redirected to the revenue withdrawal page. Here, type in the amount to withdraw and select the bank account to which the money is to be transferred (if none is associated with your account,
	you will be prompted to add one) and click the <b>Withdraw</b> button. If the transaction is successful, you will be redirected to the revenue withdrawal notification page
	where you can download the invoice.<br/>
	<b>The minimum withdrawal amount is $25.00</b>
	<br/><br/>

	<b id="api">Embedding Service In Software Product</b>
	<br/>
	Please refer to the <%= link_to "API", api_path %> page for the instructions.
	<br/><br/>

	<b id="costs">Ads Serving Costs For Publishers</b>
	<br/>
	$1 per click ($0.9 if pre-paid)<br/>
	$0.0007 per impression ($0.0006 if pre-paid)
	<br/><br/>

	<b id="ad_rev">Software Developer Revenue</b>
	<br/>
	$0.68 per click<br/>
	$0.00036 per impression
	<br/><br/>
	
	<b id="ad_block">AdBlock</b>
	<br/>
	In some browsers with the <b>AdBlock</b> enabled, the ads images will not show. If you want the ads images to appear correctly, please turn off the <b>AdBlock</b>.
	<br/><br/>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="container center">
	<h1>WELCOME TO</h1>
	<%= image_tag("logo.png", class:"logo-home")%>
	<p><b>AdPush</b> is the only online advertising service you will ever need! It provides multiple ways of displaying <i>your</i> ads to the users. Our target audience is the Android videogamers, so we provide many ways of serving the ads: images, animations, or texts; when you need them and how you need them. 
	You can retrieve the ads directly, but should you choose not to, our highly sophisticated recommender algorithm will do all the tedious work for you! <i>Isn't that great?</i></p>
	<%= link_to "Sign Up!", signup_path, class: "btn btn-lg btn-primary"%>
</div>

app/views/static_pages/terms_and_conditions.erb
<% provide(:title, 'Terms & Conditions') %>
<h1>Terms &amp; Conditions</h1>
<p>
	<b>Disclaimer</b>
	<br/>
	This service was created by Andrey Shevyakov (20055954) as the final year project for the Software Systems Development (Hons) course offered by the Waterford Insitute of Technology.
	The financial operations, such as topping up the account balance and paying the bills, are not performed in conjunction with the actual banking
	services; however, be aware that the provided payment cards' and bank accounts' information is stored in the service database, so please refrain 
	from providing real data.
	<br/><br/>

	<b>Introduction</b>
	<br/>
	These terms and conditions govern your use of this service. By using this service, you accept these terms and conditions in full. 
	If you disagree with these terms and conditions or any part of these terms and conditions, you must not use this service. 
	You must be at least 13 years of age to use this service.  By using this service and by agreeing to these terms and conditions, 
	you warrant and represent that you are at least 13 years of age.
	<br/>
	This service uses cookies.  By using this service and agreeing to these terms and conditions, you consent to use of cookies.
	<br/><br/>

	<b>License</b>
	<br/>
	The code, assets, and functionality provided by the service is the sole property of Andrey Shevyakov, unless specified otherwise. It is restricted to copy or modify the service content in 
	any manner. Under any conditions, the submitted ads content remain the intellectual property of the submitting party.
	<br/>
	The service is provided without any warranties, express or implied.
	<br/><br/>

	<b>Acceptable Use</b>
	<br/>
	You must not use this service in any way that causes, or may cause, damage to the service or impairment of the availability or accessibility of the service; or in any way which is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity.
	<br/>
	You must not use this service to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit or other malicious computer software.
	<br/>
	You must not conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction and data harvesting) on or in relation to this service without Andrey Shevyakov's express written consent.
	<br/><br/>

	<b>Restricted Access</b>
	<br/>
	Your user account may be disabled without notice or explanation.
	<br/><br/>

	<b>Limitations of Liability</b>
	<br/>
	Andrey Shevyakov is not responsible for any consequences of using the service.
	<br/><br/>

	<b>Variation</b>
	<br/>
	These terms and conditions may be revised. Revised terms and conditions will apply to the use of this service from the date of the publication of the revised terms and conditions. Please check this page regularly to ensure you are familiar with the current version.
	</br></br>

	<b>Ownership</b>
	<br/>
	The service's ownership may be transferred without notice or explanation.
	<br/><br/>
	
	<b>Contacts</b>
	<br/>
	The service's owner can be contacted at <a href="mailto:ieshevyakov@gmail.com?Subject=AdPush" target="_top">ieshevyakov@gmail.com</a>.
	<br/><br/>

	<b>Credit</b>
	<br/>
	This document was created using a modified Contractology template available at <a href="http://www.freenetlaw.com">http://www.freenetlaw.com</a>.
</p>

app/views/static_pages/uploaded.html.erb
<% provide(:title, "Ad Uploaded") %>
<h1 class="center">Ad Uploaded</h1>
<div class="container">

<div class="row center" style="margin-top:30px; margin-bottom:30px">
Ad <b>N.<%= rand(3...10)%></b> successfully uploaded!
</div>
<div class="row center">
<%= link_to "Add One More Ad!", back_path(id: 3), class: "btn btn-lg btn-primary btn-orange btn-same" %>
</div>
</div>

app/views/static_pages/verification_success.html.erb
<% @user = User.find(params[:user_id]) %>
<% begin %>
<% log_out %>
<% rescue %>
<% end %>
<% provide(:title, @user.name) %>
<h1>E-Mail Successfully Verified</h1>
<div class="container">
	Dear <% if @user.gender == 'm' %> Mr. <%= @user.name %> <%else%> Ms <%= @user.name %><%end%>, your <b><i>AdPush</i></b> account has been successfully verified.
	Now you can log in.
</div>