config/routes.rb
Rails.application.routes.draw do
  resources :ips
  resources :ads
	resources :users
	resources :tags
	resources :products
	resources :bank_infos
	resources :invoices
	resources :feedbacks
	resources :payment_cards
	resources :suggestion_tables
	
	root 'static_pages#home'
	
    get 'signup'  => 'users#new'	
    get 'details' => 'users#edit_personal_details'
    get 'preferences' => 'users#edit_preferences'
    get 'verify_email' => 'users#verify_email'
    get 'terms_and_conditions' => 'static_pages#terms_and_conditions'
    get 'help' => 'static_pages#help'
    get 'api' => 'static_pages#api'
    get 'verification_success' => 'static_pages#verification_success'
    get 'resend_verification_email' => 'users#resend_verification_email'
    get 'login' => 'sessions#new'
    post   'login'   => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'
	
	get 'inc_font' => 'users#inc_font'
	get 'dec_font' => 'users#dec_font'
	
	get 'list_tags' => 'tags#list_tags'
	get 'block_tags' => 'tags#block_tags'
	get 'block' => 'tags#block_tags_action'
    
    get 'upload' => 'ads#new'
    get 'block_ad_in_product' => 'ads#single_ad_block'
    delete 'delete_ad' => 'ads#destroy'
    get 'search' => 'ads#search'
    get 'edit' => 'ads#edit'
    
    get 'add_product' => 'products#new'
    get 'products' => 'products#index'
    get 'delete_products' => 'products#destroy'
    
    get 'add_bank_details' => 'bank_infos#new'
    get 'withdraw_revenue' => 'users#withdraw_revenue'
    post 'withdraw' => 'invoices#withdraw_revenue'
    
    get 'single_ad' => 'ads#get_ad'
    get 'random_ad' => 'ads#get_random_ad'
    get 'random_ad_tags' => 'ads#get_random_ad_by_tags'
    get 'suggested_ad' => 'ads#suggested_ad'
    get 'click_ad' => 'ads#click_ad'
    
    get 'leave_feedback' => 'feedbacks#new'
    
    get 'successful_withdrawal' => 'invoices#successful_withdrawal'
    get 'generate_invoice_pdf' => 'invoices#generate_invoice_pdf'
    
    get 'top_up' => 'users#top_up'
    post 'top_up_action' => 'users#top_up_action'
    
    get 'add_payment_card' => 'payment_cards#new'
    
    get 'pay_bills' => 'users#pay_bills'
    get 'bill_pay_invoice' => 'users#bill_pay_invoice'
    get 'generate_bill_pay_invoice_pdf' => 'users#generate_bill_pay_invoice_pdf'
    post 'pay_bills_action' => 'users#pay_bills_action'
    
    get 'performance_analysis' => 'users#performance_analysis'
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :remember_token

	validates :login, presence: true, length: { in: 3..120}, format: { with: /\A[a-zA-Z0-9]+\Z/, message: "must contain no white spaces and special characters"}
	validates :name, presence: true, length: { in: 4..120}
	validates_length_of :name, minimum: 2, too_short: 'must be provided', tokenizer: ->(str) { str.scan(/\w+/) }
	validates :company, presence: true, length: { in: 2..120}
	validates :dob, presence: true, date: {after: Proc.new {Time.now - 100.years}, message: "must enter a valid date of birth"}
	validates :dob, date: {before: Proc.new {Date.today - 18.years}, message: "have to be at least 18 years old to use the service"}
	validates :state, presence: true
	validates :city, presence: true, length: {in: 2..57}
	validates :zip, presence: true
	validates :address, presence: true, length: {in: 10..200}

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
					format: { with: VALID_EMAIL_REGEX },
					uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }, :on => :create
	validates :password_confirmation, presence: true, :on => :create
	validates :password, presence: true, length: { minimum: 6 }, :on => :update, :allow_blank => true
	validates :password_confirmation, presence: true, :on => :update, :allow_blank => true

	has_secure_password

	validate :unique_company

	has_many :bank_infos, :foreign_key => 'user_id'
	has_many :bills, :foreign_key => 'user_id'
	has_many :payment_cards, :foreign_key => 'user_id'
	has_many :products, :foreign_key => 'user_id'
	has_many :feedbacks, :foreign_key => 'user_id'

	def unique_company
	company_c = self.company.strip.split.map(&:capitalize).join(' ')
	if self.company_was != company_c
		User.all.each do |u|
			if company_c == u.company and self.utype == u.utype
				errors.add(:company, 'must be unique')
				break
			end
		end
	end
	end

	# Returns the hash digest of a string.
	def User.digest(string)
	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
												  BCrypt::Engine.cost
	BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token.
	def User.new_token
	SecureRandom.urlsafe_base64
	end

	# Remembers a user in the database for use in persistent sessions.
	def remember
	self.remember_token = User.new_token
	update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated?(remember_token)
	begin
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	rescue
		false
	end
	end

	def forget
	  update_attribute(:remember_digest, nil)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		# Check if someone logged in
		if current_user != nil
			current_user.id 
			flash[:success] = "You Are Already Registered"
			redirect_to root_path
		else
			@user = User.new
		end
	end

	def show
		restrict_access
		@user = User.find(params[:id])
		if current_user.id != @user.id
			redirect_to root_path
		end
		begin
			@ads = Ad.where(:publisher => @user.id)
		rescue
		end
		if Bill.where("created_at < ?", Time.mktime(Date.today.year, Date.today.month)).where(paid: false).where(user_id: @user.id).length > 0
			flash.now[:error] = "Bills For Previous Months Unpaid - Published Ads Won't Be Served"
		end
	end

	def create
		secure_params = params.require(:user).permit(:login, 
		:email, :email_verification_key, :utype, :name, :company, :gender, :dob,
		:country, :state, :city, :address, :zip,
		:password, :password_confirmation)
		secure_params[:gender] = secure_params[:gender].downcase[0]
		secure_params[:email_verification_key] = SecureRandom.random_number(36**12).to_s(36).rjust(12, "0")
		secure_params[:login] = secure_params[:login].downcase.strip 
		secure_params[:email] = secure_params[:email].downcase
		secure_params[:name] = secure_params[:name].strip.split.map(&:capitalize).join(' ')
		secure_params[:company] = secure_params[:company].strip.split.map(&:capitalize).join(' ')
		secure_params[:state] = secure_params[:state].strip.capitalize
		secure_params[:city] = secure_params[:city].strip.capitalize
		secure_params[:address] = secure_params[:address].strip.capitalize
		
		@user = User.new(secure_params)
		
		if @user.save  
			if @user.utype == 0
				Bill.new(user_id: @user.id, amount: 0, paid: false).save
			end
			remember @user     
			flash[:success] = "Welcome to AdPush!"  
			send_verification_email(@user)
		else
			render 'new' 
		end
	end

	def edit_preferences
		extra_protection
	end

	def edit_personal_details
		extra_protection
	end

	def update
		@user = User.find(params[:id])
		
		if params[:email_update] == "y"
			secure_params = params.require(:user).permit(:email)
			secure_params[:email] = secure_params[:email].downcase
			
			unique_email = true
			
			User.all.each do |u|
				if u.email == secure_params[:email]
					unique_email = false
				end
			end
			
			if unique_email
				@user.update_attribute(:email, secure_params[:email])
				@user.update_attribute(:email_verification_key, SecureRandom.random_number(36**12).to_s(36).rjust(12, "0"))
				flash[:changed] = "Email Successfully Changed"
				send_verification_email(@user)
			else
				flash[:error] = "Email Already Registered"
				redirect_to @user
			end

		elsif params[:prefs_update] == "y"
			secure_params = params.require(:user).permit(:color_scheme, :font_size)
			@user.update_attribute(:color_scheme, secure_params[:color_scheme])
			@user.update_attribute(:font_size, secure_params[:font_size])
			flash[:success] = "Preferences Updated"
			redirect_to preferences_path

		else
			old_password = params.permit(:old_password)

			if @user and @user.authenticate(old_password[:old_password]) 
				old_email = @user.email
				secure_params = params.require(:user).permit(:name, :gender, :dob, :country, :state, :city, :zip, :address, :email, :password, :password_confirmation)
		
				@user.update_attributes(secure_params)
				if @user.save  
					remember @user     
					flash[:changed] = "Personal Details Updated"  
					if old_email != @user.email	
						send_verification_email(@user)
					end
					remember @user     
					begin
						redirect_to @user
					rescue
					end
				else
					render 'edit_personal_details'
				end
			else
				flash[:error] = "Invalid Password"
				render 'edit_personal_details'
			end
		end
	end

	def send_verification_email(user)
		@user = user
		begin
			EmailVerificationMailer.verification_email(@user).deliver
		rescue
			@user.update_attribute(:email_verification_key, SecureRandom.random_number(36**12).to_s(36).rjust(12, "0"))
			EmailVerificationMailer.verification_email(@user).deliver
		end
		flash[:success] = "Verification Email Sent" 
		redirect_to @user
	end

	def resend_verification_email
		@user = User.find(params[:user_id])
		EmailVerificationMailer.verification_email(@user).deliver
		flash[:success] = "Repeat Verification Email Sent" 
		redirect_to @user
	end

	def verify_email
		begin
			@user = User.find_by_email_verification_key(params[:email_verification_key])
			@user.update_attribute(:email_verification_key, nil)
			redirect_to verification_success_path(user_id: @user.id)
		rescue
			redirect_to root_path
		end
	end

	def inc_font
		if (current_user.font_size < 2)
			current_user.update_attribute(:font_size, current_user.font_size + 1)
		end
	end

	def dec_font
		if (current_user.font_size != 0)
			current_user.update_attribute(:font_size, current_user.font_size - 1)
		end
	end

	def withdraw_revenue
		restrict_access
		
		begin
			restrict_non_verified_access
		rescue
			redirect_to root_path
		end
		
		if current_user.utype == 0 or current_user.balance < 25
			redirect_to root_path
		end
		
		@user = current_user
		@invoice = Invoice.new 
	end

	# Render top up page
	def top_up
		restrict_access
		
		begin
			restrict_non_verified_access
		rescue
			redirect_to root_path
		end
		
		if current_user.utype == 1
			redirect_to root_path
		end
		
		@user = current_user
	end

	# Top up
	def top_up_action
		# Due to the study nature of the project, no interaction was carried out with the actual banking services.
		restrict_access
		@top_up = params[:top_up_amount][1..params[:top_up_amount].length].to_f
		current_user.update_attribute(:balance, current_user.balance + @top_up)
		flash[:success]="Successful Top Up!"
		redirect_to current_user
	end

	# Render bill pay page
	def pay_bills
		restrict_access
		@user = current_user
	end

	# Pay bills
	def pay_bills_action
		# Due to the study nature of the project, no interaction was carried out with the actual banking services.
		restrict_access
		@bill = Bill.find(params[:bill])
		
		if @bill.user_id == current_user.id
			redirect_to bill_pay_invoice_path(bill_id: @bill.id)
		else
			redirect_to root_path
		end
	end

	# Bill pay invoice page
	def bill_pay_invoice
		restrict_access
		@user = current_user
		@bill = Bill.find(params[:bill_id])
		
		if @bill.paid == true 
			redirect_to current_user
		else
			if @user.id != @bill.user_id
				redirect_to root_path
			else
				@bill.update_attribute(:paid, true)
			end
		end
	end

	def generate_bill_pay_invoice_pdf
		@bill = Bill.find(params[:bill])   
		pdf = Prawn::Document.new
		pdf.stroke_horizontal_rule
		pdf.pad(10) { pdf.text "AdPush", :align => :left}
		pdf.text "Invoice / " + Date.today.to_s, :align => :left
		pdf.stroke_horizontal_rule
		pdf.move_cursor_to 710
		pdf.text "Random Street 40, Waterford, Co. Waterford, Ireland", :align => :right
		pdf.move_cursor_to 650
		pdf.stroke_horizontal_rule 
		pdf.pad(10) { pdf.text current_user.name, :align => :left }
		pdf.move_cursor_to pdf.cursor+25
		pdf.text "Balance Due", :align => :right
		pdf.text "Upon Receipt", :align => :right
		pdf.text "$" + @bill.amount.to_s, :align => :right
		pdf.move_cursor_to pdf.cursor+10
		pdf.bounding_box([0,pdf.cursor],:width=>200) do
			pdf.text current_user.address + ", " + current_user.state + ", " + current_user.country, :align => :left 
		end
		pdf.stroke_horizontal_rule 
		pdf.move_cursor_to pdf.cursor-20
		pdf.table([["Item Description", "Quantity", "Price Per Item", "Total"], ["Bill Payment For " + @bill.created_at_label + " Time Period", "1","$" + @bill.amount.to_s,"$" + @bill.amount.to_s]])
		pdf.move_cursor_to 20
		pdf.text "AdPush©, " + Date.today.year.to_s, :align => :center
		send_data pdf.render, filename: 'invoice.pdf', type: 'application/pdf'
	end

	def performance_analysis
		restrict_access
		
		begin
			restrict_non_verified_access
		rescue
			redirect_to root_path
		end
	end

private

	def extra_protection
		restrict_access
		if current_user != nil
			@user = User.find(current_user.id)
			if current_user.id != @user.id
				redirect_to root_path
			end
			restrict_non_verified_access
		end
	end

end

app/views/users/bill_pay_invoice.html.erb
<% provide(:title, @user.name + " - Bill Payment") %>
<h1>Bill Payment</h1>
<div class="container">
	<div class="row">
		<%= @bill.created_at_label %> bill was successfully paid.
	</div>
	<div class="row">
		<%= link_to "Download Invoice", generate_bill_pay_invoice_pdf_path(:bill => @bill), class: "btn btn-primary " %>
	</div>
	<div class="row">
		<%= link_to "Return To Control Panel", current_user, class: "btn btn-primary " %>
	</div>
</div>

app/views/users/edit_preferences.html.erb
<% provide(:title, @user.name + " - Preferences") %>
<h1>Preferences</h1>
<div class="container">

<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>   

		<div class="row">
			<%= f.label :color_scheme, "Color Scheme:", class: "fr" %>
			<%= f.select :color_scheme, options_for_select([['Orange', 0], ['Silver', 1]], @user.color_scheme) %>
		</div>
		
		<div class="row">
			<%= f.label :font_size, "Font Size:", class: "fr" %>
			<%= f.select :font_size, options_for_select([['Normal', 0], ['Large', 1], ['Largest', 2]], @user.font_size) %>
		</div>

		<%= hidden_field_tag :prefs_update, "y" %>
		
		<div class="row">		
			<%= f.submit "Save Changes", class: "btn btn-primary " %>
		</div>
<% end %>

</div>

app/views/users/pay_bills.html.erb
<% provide(:title, @user.name + " - Bills") %>
<h1>Bills</h1>
<div class="container">
	<% if Bill.where("created_at < ?", Time.mktime(Date.today.year, Date.today.month)).where(paid: false).where(user_id: @user.id).length > 0 %>
	<%= form_tag pay_bills_action_path do %>
	<% if @user.payment_cards.length == 0 %>
	<div class="row">
		Please, <%=link_to "add a payment card", add_payment_card_path(:bill_pay => true)%> to proceed.
	</div>
	<% else %>
	<div class="row">
		<%= label_tag :bill, "Bill:", class: "fr" %>
		<%= select_tag :bill, options_from_collection_for_select(@user.bills.where("created_at < ?", Time.mktime(Date.today.year, Date.today.month)).where(paid: false), "id", "created_at_label") %>
	</div>
	<div class="row">
		<%= label_tag :payment_card, "Payment Card:", class: "fr" %>
		<%= select_tag :payment_card, options_from_collection_for_select(@user.payment_cards, "id", "card_num") %>
	</div>
	<div class="row">
		<%=link_to "Add Payment Card", add_payment_card_path(:bill_pay => true), class: "btn btn-primary  nmb"%>
	</div>
	<div class="row">
		<%= label_tag :cvv, "CVV/CVC:", class: "fr" %>
		<%= text_field_tag :cvv %>
	</div>
	<% end %>
	<% if @user.payment_cards.length != 0 %>
	<div class="row">
		<%= submit_tag "Pay The Bill", class: "btn btn-primary ", id: "bill-pay-btn", disabled: "disabled"%>
	</div>
	<% end %>
	<% end %>
	<% else %>
	You Have No Bills To Pay.
	<% end %>
</div>

<%=javascript_include_tag "inline/bill_pay_listener"%>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% @tc = Tag.count %>
<% if @user.email_verification_key != nil %>
<h1>Email Verification</h1>
<% else %>
<h1>Control Panel</h1>
<% end %>
<div class="container">
<% if @user.email_verification_key != nil %>
Please verify your email to continue.<br/>
If you can't find it, make sure you checked the "Spam" folder.</br>
Alternatively, <%= link_to "request repeat verification email", resend_verification_email_path(user_id: @user.id) %>.
<br/><br/>
If no recommendation listed above works, you can also change your email address: 
<br/>
<div id="email-change-form">
<%= form_for(@user) do |f| %>
<%= f.label :email, "New email:" %>
<%= f.email_field :email %>
<%= hidden_field_tag :email_update, "y" %>
<%= f.submit "Change Email"  %>
<% end %>
</div>
<% else %>
<div class="row"> 
<%= form_tag(search_path, :method => "get", id: "search-form") do %>
<div class="input-append">
<% if cookies[:search_query] == nil %>
<%= text_field_tag :search, params[:search], id: "search-bar", placeholder: "Search Ads" %>
<% else %>
<%= text_field_tag :search, params[:search], id: "search-bar", placeholder: "Search Ads", value: cookies[:search_query].strip%>
<% end %>
<button type="submit" id="search-submit-btn"><i class="glyphicon glyphicon-search"></i></button>
</div>
<%= check_box_tag :show_images, params[:show_images], checked: "unchecked"%>
<span>Display Images</span>
<% end %>
</div>
<% if cookies[:search_request] == "true" %>
<div class="row search-results">
<% search_results(cookies[:search_query]) %>
<% if @ads.length != 0 %>
<ul class="ads-list">
<% @ads.each do |a| %>
<% if a.desc.length <= 60 %>
<li>
<%= link_to a.desc + " - " + a.link, a, class: "btn " %>
<% if cookies[:show_images] == "on" %>
<div class="search-img-area">
<%= image_tag a.content.url, class:"ad-img ad-img-small" %>
</div>
<% else %>
<% end %>
<% if a.publisher == current_user.id %>
<%= link_to image_tag("remove.png", size: "32x32", alt: "Remove Ad", class: "btn btn-delete-ad"), delete_ad_path(:id => a.id), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<% if current_user.utype == 1 and current_user.products.length != 0%>
<div class="block_selection container" id="<%=a.id%>">
<% ad_blocked_in_products(a.id)%>


<ul class="products-list <%=a.id%>">

<% @unblock = true %>
<% current_user.products.each do |p| %>


<% if @block_list.include? p.id %>
<li class="<%=a.id%> btn btn-product-selected">
<% else %>
<% @unblock = false %>
<li class="<%=a.id%> btn btn-product">
<% end %>


<% if p.title.length <= 60 %>
<%= p.title %>
<% else %>
<%= p.title[0..60] + "..." %>
<% end %>
</li>
<% end %>
</ul>
<span class="btn ad-block-btn btn-primary <%=a.id%>">Block Ad In Selected Products</span>
</div>
<% if @unblock == false %>
<%= image_tag("block.png", size: "32x32", alt: "Block Ad", class: "btn btn-block-ad " + a.id, data: {toggle: "tooltip"}, title: "Block ad in some products") %>
<% else %>
<%= image_tag("unblock.png", size: "32x32", alt: "Unblock Ad", class: "btn btn-block-ad " + a.id, data: {toggle: "tooltip"}, title: "Unblock ad in some products") %>
<% end %>
<% end %>
</li>
<% else %>
<li><%= link_to a.desc[0..60] + "... - " + a.link, a, class: "btn " %></li>
<% end %>
<% end %>
</ul>
</div>
<% else %>
<div class="search-results no-search-results">
No Relevant Ads
</div>
</div>
<%end%>
<div class="row">
<span class="btn btn-primary btn-hide">Hide Search Results</span>
</div>
<% if @tc > 0 %>
<hr/>
<% end %>
<% cookies[:search_request] = nil %>
<% else %>
<% end %>

<div class="row">
<% if @tc > 0 %>
<%= link_to "List All Tags", list_tags_path, class: "btn btn-primary" %>
<% end %>
</div>
<hr class="main-divider"/>
<% if @user.utype == 0 %>
<div class="row">Current Month Billing: $<%=Bill.where("created_at >= ? and created_at < ?", Time.mktime(Date.today.year, Date.today.month), Time.mktime(Date.today.year, Date.today.month + 1)).find_by_user_id(@user.id).amount%></div>
<div class="row">Prepaid Balance: $<%=@user.balance%></div>
<% if Bill.where("created_at < ?", Time.mktime(Date.today.year, Date.today.month)).where(paid: false).where(user_id: @user.id).length > 0 %>
<div class="row"><%= link_to "Pay Bills", pay_bills_path, class: "btn btn-primary btn-pay-bills"%></div>
<% end %>
<div class="row"><%= link_to "Top Up", top_up_path, class: "btn btn-primary "%></div>
<div class="row"><%= link_to "Add Payment Card", add_payment_card_path, class: "btn btn-primary nmb"%></div>
<div class="row"><%= link_to "Upload New Ad", upload_path, class: "btn btn-primary "%></div>
<% end %>
<% if @user.utype == 1 %>
<div class="row"><%=link_to "Add Bank Account", add_bank_details_path, class: "btn btn-primary " %></div>
<% end %>
<% if Ad.count != 0 %>
<div class="row"><%= link_to "Performance Analysis", performance_analysis_path, class: "btn btn-primary " %></div>
<% end %>
<div class="row"><%= link_to "Edit Personal Details", details_path, class: "btn btn-primary " %></div>
<div class="row"><%= link_to "Edit Preferences", preferences_path, class: "btn btn-primary " %></div>
<hr class="main-divider"/>
<% if @user.utype == 0 and @ads != nil %>
<div class="row"><h2>Published Ads</h2></div>
<div class="row">
<span class="btn btn-primary" id="toggle-published-ads">Show</span>
</div>
<div class="row published-ads-area">
<ul class="ads-list">
<% puts @ads %>
<% @ads.each do |a| %>
<% if a.desc.length <= 60 %>
<li><%= link_to a.desc + " - " + a.link, a, class: "btn " %>
<% else %>
<li><%= link_to a.desc[0..60] + "... - " + a.link, a, class: "btn " %>
<% end %>
<%= link_to image_tag("remove.png", size: "32x32", alt: "Remove Ad", class: "btn btn-delete-ad"), delete_ad_path(:id => a.id), method: :delete, data: { confirm: 'Are you sure?' } %></li>
<% end %>
<% end %>
</ul>
<% if @user.utype == 1 %>
<div class="row" style="margin-top: 15px;">
<span>Current balance: $<%=@user.balance%></span>
</div>
<div class="row">
<% if @user.balance < 25 %>
<%= link_to "Withdraw Revenue", withdraw_revenue_path, class: "btn btn-primary ", disabled: "disabled", data: {toggle: "tooltip"}, title: "Insufficient funds (must be more than $25)" %>
<% else %>
<%= link_to "Withdraw Revenue", withdraw_revenue_path, class: "btn btn-primary "%>
<% end %>
</div>
<div class="row">
<%= link_to "List Software Products", products_path, class: "btn btn-primary " %>
</div>
<div class="row">
<%= link_to "Add New Software Product", add_product_path, class: "btn btn-primary " %>
</div>
<% end %>
</div>
<% end %>

<%= hidden_field_tag :checkbox_checked, cookies[:show_images] %>
<%=javascript_include_tag "jquery.bpopup.min"%>
<%=javascript_include_tag "inline/single_ad_block_listener"%>
<%=javascript_include_tag "inline/products_block_single_ad"%>
<%=javascript_include_tag "inline/published_ads_hide_listener"%>
<%=javascript_include_tag "inline/search_results_hide_listener"%>
<%=javascript_include_tag "inline/blank_search_listener"%>
<%=javascript_include_tag "inline/checkbox_state_setter"%>
<%=javascript_include_tag "inline/image_show_listener"%>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/users/top_up.html.erb
<% provide(:title, @user.name + " - Top Up") %>
<h1>Top Up</h1>

<%= form_tag top_up_action_path do %>
	<div class="row"><%= label_tag :payment_card, "Payment Card:", class: "fr" %></div>
	<% if @user.payment_cards.length == 0 %>
		<div class="row"><span>Please, <%=link_to "add a payment card", add_payment_card_path(:top_up => true)%> to proceed.</span></div>
	<% else %>
		<div class="row"><%= select_tag :payment_card, options_from_collection_for_select(@user.payment_cards, "id", "card_num") %></div>
		<div class="row"><%=link_to "Add Payment Card", add_payment_card_path(:top_up => true), class: "btn btn-primary nmb"%></div>
		<div class="row">
			<%= label_tag :cvv, "CVV/CVC:", class: "fr" %>
			<%= text_field_tag :cvv %>
			<%= label_tag :top_up_amount, "Top Up Amount:", class: "fr" %>
			<%= text_field_tag :top_up_amount, '$0' %>
		</div>
	<%end%>
	<div class="row"><%= submit_tag "Top Up", class: "btn btn-primary ", id: "top-up-btn", disabled: "disabled" %></div>
<% end %>

<%=javascript_include_tag "inline/top_up_listener"%>

app/views/users/withdraw_revenue.html.erb
<% provide(:title, @user.name + " - Revenue Withdrawal") %>
<h1>Revenue Withdrawal</h1>
<div class="container">
		<div class="row">
		<%= form_for @invoice, :url => withdraw_path do |f| %>
			<%= label_tag :amount_to_withdraw, "Withdrawal Amount:", class: "fr" %>
			<%= text_field_tag :amount_to_withdraw, @user.balance %>
			<%= label_tag :bank_acc, "Bank Account:", class: "fr" %>
			<% if @user.bank_infos.length == 0 %>
				Please, <%=link_to "add a bank account", add_bank_details_path(:from_withdrawal => true)%> to proceed.
			<% else %>
				<%= select_tag :bank_acc, options_from_collection_for_select(@user.bank_infos, "id", "account_number") %>
			<% end %>
		</div>
		<% if @user.bank_infos.length > 0 %>
			<div class="row"><%= link_to "Add Bank Account", add_bank_details_path(:from_withdrawal => true), class: "btn btn-primary "%></div>
		<% end %>
		<div class="row">
			<% if @user.bank_infos.length == 0 %>
				<%=f.submit "Withdraw", class: "btn btn-primary btn-withdraw", disabled: "disabled"%>
			<% else %>
				<%=f.submit "Withdraw", class: "btn btn-primary btn-withdraw"%>
			<% end %>
		<% end %>
		</div>
</div>

<%=javascript_include_tag "inline/withdrawal_sum_listener"%>