config/routes.rb
Rails.application.routes.draw do
  resources :ips
  resources :ads
	resources :users
	resources :tags
	resources :products
	resources :bank_infos
	resources :invoices
	resources :feedbacks
	resources :payment_cards
	resources :suggestion_tables
	
	root 'static_pages#home'
	
    get 'signup'  => 'users#new'	
    get 'details' => 'users#edit_personal_details'
    get 'preferences' => 'users#edit_preferences'
    get 'verify_email' => 'users#verify_email'
    get 'terms_and_conditions' => 'static_pages#terms_and_conditions'
    get 'help' => 'static_pages#help'
    get 'api' => 'static_pages#api'
    get 'verification_success' => 'static_pages#verification_success'
    get 'resend_verification_email' => 'users#resend_verification_email'
    get 'login' => 'sessions#new'
    post   'login'   => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'
	
	get 'inc_font' => 'users#inc_font'
	get 'dec_font' => 'users#dec_font'
	
	get 'list_tags' => 'tags#list_tags'
	get 'block_tags' => 'tags#block_tags'
	get 'block' => 'tags#block_tags_action'
    
    get 'upload' => 'ads#new'
    get 'block_ad_in_product' => 'ads#single_ad_block'
    delete 'delete_ad' => 'ads#destroy'
    get 'search' => 'ads#search'
    get 'edit' => 'ads#edit'
    
    get 'add_product' => 'products#new'
    get 'products' => 'products#index'
    get 'delete_products' => 'products#destroy'
    
    get 'add_bank_details' => 'bank_infos#new'
    get 'withdraw_revenue' => 'users#withdraw_revenue'
    post 'withdraw' => 'invoices#withdraw_revenue'
    
    get 'single_ad' => 'ads#get_ad'
    get 'random_ad' => 'ads#get_random_ad'
    get 'random_ad_tags' => 'ads#get_random_ad_by_tags'
    get 'suggested_ad' => 'ads#suggested_ad'
    get 'click_ad' => 'ads#click_ad'
    
    get 'leave_feedback' => 'feedbacks#new'
    
    get 'successful_withdrawal' => 'invoices#successful_withdrawal'
    get 'generate_invoice_pdf' => 'invoices#generate_invoice_pdf'
    
    get 'top_up' => 'users#top_up'
    post 'top_up_action' => 'users#top_up_action'
    
    get 'add_payment_card' => 'payment_cards#new'
    
    get 'pay_bills' => 'users#pay_bills'
    get 'bill_pay_invoice' => 'users#bill_pay_invoice'
    get 'generate_bill_pay_invoice_pdf' => 'users#generate_bill_pay_invoice_pdf'
    post 'pay_bills_action' => 'users#pay_bills_action'
    
    get 'performance_analysis' => 'users#performance_analysis'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="row">
		<div class="col-md-6">AdPush, 2015 - 2016</div>
		<div class="col-md-6" style="text-align:right;">
		<%= link_to "Terms & Conditions", terms_and_conditions_path %>
		<%= link_to "Contact Us", leave_feedback_path, style:"margin-left:15px;" %>
		<%= link_to "Help", help_path, style:"margin-left:15px;" %>
		<%= link_to "API", api_path, style:"margin-left:15px;" %>
		</div>
	</div>
	<div id="font-size-change-container">
		<%= image_tag("font_increase.png", :alt => "Increase Font Size", :id => "font-increase-button") %>
		<%= image_tag("font_decrease.png", :alt => "Decrease Font Size", :id => "font-decrease-button") %>
	</div>
</footer>
<%=javascript_include_tag "inline/font_size_change_listener"%>
<% begin %>
<span style="display: none;" id="font-size-val"><%=current_user.font_size%></span>
<% rescue %>
<span style="display: none;" id="font-size-val">0</span>
<% end %>

app/views/layouts/_header.html.erb
<%= javascript_include_tag 'js.cookie' %>
<%= javascript_include_tag "inline/cookies_warning"%>
<%= stylesheet_link_tag 'common' %>
<%= stylesheet_link_tag 'jquery-ui.min' %>
<%= stylesheet_link_tag 'jquery.multiselect' %>
<% begin %>
	<% if current_user.color_scheme == 0 %>
	<%= stylesheet_link_tag 'orange' %>
	<% else %>
	<%= stylesheet_link_tag 'silver' %>
	<% end %>
	<% rescue %>
	<%= stylesheet_link_tag 'orange' %>
<% end %>
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<nav>
			<a href="/"><%= image_tag("logo.png")%></a>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<% if logged_in? %>
				<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				Account <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "Control Panel", current_user %></li>
					<li class="divider"></li>
					<li>
					<%= link_to "Log out", logout_path, method: "delete" %>
					</li>
				</ul>
				</li>
				<% else %>
				<li><%= link_to "Log in", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
 <html>
 
	 <head>
		 <title>AdPush | <%= yield(:title) %></title>
		 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		 <%= csrf_meta_tags %>
		 <!--[if lt IE 9]>
		 <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
		 </script>
		 <![endif]-->
	 </head>
	 
	 <body data-no-turbolink="true">
		 <div class="container">
		 <%= render 'layouts/header' %>
		 <% flash.each do |message_type, message| %>   
		 <div class="alert alert-<%= message_type %>"><%= message %></div>
		 <% end %>                                     
		 <%= yield %>
		 <%= render 'layouts/footer' %>
	 	</div>
	 </body>
 
 </html>